### ISSUE TITLE
Remove debug output to stdout

### ISSUE THREAD

**Issue by svetlyak40wt** [bessarabov/App-AllMyChangesUtils#2]
When you do, as documentation says: 

```
./bin/get_github_favorites svetlyak40wt > list
```

Script waves such lines to the `list` file:

```
https://api.github.com/users/svetlyak40wt/starred
https://api.github.com/user/24827/starred?page=2
https://api.github.com/user/24827/starred?page=3
...
```

If this ouput is really needed, it is better to write it to STDERR.

**Comment by bessarabov** [comment]
Thank you! Fixed in https://github.com/bessarabov/App-AllMyChangesUtils/commit/a5bb5c4680def4b5fa9694d3596bfd35fbb1c2c6 and released in version 1.0.5 (on its way to cpan, usually it takes about an hour to appeare on cpan)
